#! /bin/sh

wal -i /home/alex/backgrounds
polybar example &

bspc monitor -d I II III IV

bspc config border_width         1
bspc config window_gap		6 

bspc config split_ratio          0.61
bspc config borderless_monocle   true
bspc config gapless_monocle      true

